"""fix #110

Copyright 2019, Grid.
This source code is licensed under the ReNom Subscription Agreement, version 1.0.
ReNom Subscription Agreement Ver. 1.0 (https://www.renom.jp/info/license/index.html)

Revision ID: 1b5fa6c3c388
Revises: 2c2d0baf4e03
Create Date: 2019-07-18 18:21:18.773780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5fa6c3c388'
down_revision = '2c2d0baf4e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_def', sa.Column('filename_X_2', sa.TEXT(), nullable=True))
    op.add_column('dataset_def', sa.Column('filename_X_3', sa.TEXT(), nullable=True))
    op.add_column('dataset_def', sa.Column('filename_y_2', sa.TEXT(), nullable=True))
    op.add_column('dataset_def', sa.Column('filename_y_3', sa.TEXT(), nullable=True))
    # #110での更新ですが、drop_columnが正常動作しないため、元の方から削除対応します。
    # op.drop_column('dataset_def', 'filename_y')
    # op.drop_column('dataset_def', 'filename_X')
    # op.drop_column('dataset_def', 'selected_scaling')
    op.add_column('model', sa.Column('selected_scaling', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'selected_scaling')
    # op.add_column('dataset_def', sa.Column('selected_scaling', sa.INTEGER(), nullable=True))
    # op.add_column('dataset_def', sa.Column('filename_X', sa.TEXT(), nullable=True))
    # op.add_column('dataset_def', sa.Column('filename_y', sa.TEXT(), nullable=True))
    op.drop_column('dataset_def', 'filename_y_3')
    op.drop_column('dataset_def', 'filename_y_2')
    op.drop_column('dataset_def', 'filename_X_3')
    op.drop_column('dataset_def', 'filename_X_2')
    # ### end Alembic commands ###
