"""add_true_pred_histogram

Copyright 2019, Grid.
This source code is licensed under the ReNom Subscription Agreement, version 1.0.
ReNom Subscription Agreement Ver. 1.0 (https://www.renom.jp/info/license/index.html)

Revision ID: 83b33c9bb091
Revises: e8b6391f50bf
Create Date: 2018-12-20 10:41:50.923273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b33c9bb091'
down_revision = 'e8b6391f50bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('pred_histogram', sa.BLOB(), nullable=True))
    op.add_column('model', sa.Column('true_histogram', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'true_histogram')
    op.drop_column('model', 'pred_histogram')
    # ### end Alembic commands ###
