"""add paramsearcher

Copyright 2019, Grid.
This source code is licensed under the ReNom Subscription Agreement, version 1.0.
ReNom Subscription Agreement Ver. 1.0 (https://www.renom.jp/info/license/index.html)

Revision ID: e8b6391f50bf
Revises: a22b45bfd754
Create Date: 2018-12-04 20:25:35.717389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b6391f50bf'
down_revision = 'a22b45bfd754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paramsearcher',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('info', sa.BLOB(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('paramsearchermodel',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('searcher_id', sa.Integer(), nullable=False),
                    sa.Column('model_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
                    sa.ForeignKeyConstraint(['searcher_id'], ['paramsearcher.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paramsearchermodel')
    op.drop_table('paramsearcher')
    # ### end Alembic commands ###
