"""update_model

Copyright 2019, Grid.
This source code is licensed under the ReNom Subscription Agreement, version 1.0.
ReNom Subscription Agreement Ver. 1.0 (https://www.renom.jp/info/license/index.html)

Revision ID: ca4a3a6fed87
Revises: 710ce1a59d37
Create Date: 2018-11-12 09:32:50.450037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4a3a6fed87'
down_revision = '710ce1a59d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('sampled_train_pred', sa.BLOB(), nullable=True))
    op.add_column('model', sa.Column('sampled_train_true', sa.BLOB(), nullable=True))
    op.add_column('model', sa.Column('confidence_data', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'sampled_train_pred')
    op.drop_column('model', 'sampled_train_true')
    op.drop_column('model', 'confidence_data')
    # ### end Alembic commands ###
