"""#42

Copyright 2019, Grid.
This source code is licensed under the ReNom Subscription Agreement, version 1.0.
ReNom Subscription Agreement Ver. 1.0 (https://www.renom.jp/info/license/index.html)

Revision ID: 1b16a19827b2
Revises: 4e2cc619c7bf
Create Date: 2019-02-19 16:16:34.135974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b16a19827b2'
down_revision = '4e2cc619c7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('model_pickle', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'model_pickle')
    # ### end Alembic commands ###
