"""#90

Copyright 2019, Grid.
This source code is licensed under the ReNom Subscription Agreement, version 1.0.
ReNom Subscription Agreement Ver. 1.0 (https://www.renom.jp/info/license/index.html)

Revision ID: 2c2d0baf4e03
Revises: 6cb95f3b3377
Create Date: 2019-04-11 13:38:32.554894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2d0baf4e03'
down_revision = '6cb95f3b3377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('valid_confidence_data', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'valid_confidence_data')
    # ### end Alembic commands ###
