"""init

Copyright 2019, Grid.
This source code is licensed under the ReNom Subscription Agreement, version 1.0.
ReNom Subscription Agreement Ver. 1.0 (https://www.renom.jp/info/license/index.html)

Revision ID: a1643f735a26
Revises:
Create Date: 2018-11-07 14:02:30.801900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1643f735a26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_def',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.TEXT(), nullable=True),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('target_column_id', sa.Integer(), nullable=True),
                    sa.Column('labels', sa.BLOB(), nullable=True),
                    sa.Column('train_ratio', sa.FLOAT(), nullable=True),
                    sa.Column('train_index', sa.BLOB(), nullable=True),
                    sa.Column('valid_index', sa.BLOB(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('model',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('dataset_id', sa.Integer(), nullable=True),
                    sa.Column('state', sa.Integer(), nullable=True),
                    sa.Column('algorithm', sa.Integer(), nullable=True),
                    sa.Column('algorithm_params', sa.BLOB(), nullable=True),
                    sa.Column('batch_size', sa.Integer(), nullable=True),
                    sa.Column('epoch', sa.Integer(), nullable=True),
                    sa.Column('train_loss_list', sa.BLOB(), nullable=True),
                    sa.Column('valid_loss_list', sa.BLOB(), nullable=True),
                    sa.Column('best_epoch', sa.Integer(), nullable=True),
                    sa.Column('best_epoch_valid_loss', sa.FLOAT(), nullable=True),
                    sa.Column('best_epoch_rmse', sa.FLOAT(), nullable=True),
                    sa.Column('best_epoch_max_abs_error', sa.FLOAT(), nullable=True),
                    sa.Column('best_epoch_r2', sa.FLOAT(), nullable=True),
                    sa.Column('valid_predicted', sa.BLOB(), nullable=True),
                    sa.Column('valid_true', sa.BLOB(), nullable=True),
                    sa.Column('weight', sa.TEXT(), nullable=True),
                    sa.Column('deployed', sa.Integer(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_def.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    op.drop_table('dataset_def')
    # ### end Alembic commands ###
